// This file is auto-generated by grammY i18n CLI 0.1
// Changes made to this file will be overwritten.

type Value = string | number | Date;
export type GeneratedLocalesData = {
    locales: string;
    messages: {
        "message": {
            "theme": Value;
        };
        "message.key": never;
        "message.keyx": never;
        "create": never;
        "cooked.hype": {
            "file2": Value;
        };
        "coo": {
            "lastChecked": Value;
        };
        "coo.k": never;
        "maker": never;
        "pop": never;
        "poppyx": never;
    };
};